baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Jan's Blog "
sectionPagesMenu = 'main'
theme = 'ananke'
enableEmoji = true



[markup]
  defaultMarkdownHandler = 'goldmark'

[params]
  [params.contact]
    email = 'willbeforwardedtome.oasis081@passmail.net'

